In [2]:
import numpy as np

In [6]:
q1 = np.array([
    [200,220,250],
    [150,180,210],
    [300,330,360]
])
q2 = np.array([
    [209,231,259],
    [155,192,222],
    [310,340,375]
])

add two

In [8]:
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [9]:
q2 -q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

to find the growth percentage from q1 to q2

In [10]:
 (q2 - q1)/q1 * 100

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

to find the revenue of the q1

In [11]:
prices = np.array([
    [10,12,11], # prices for product a in different region
    [8,9,10],   #product b
    [15,16,17]  #product c
])
q1_revenue = q1 *prices
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

if discount amount added

In [15]:
q1_discounts = q1_revenue *20/100
q1_discounts

array([[ 400.,  528.,  550.],
       [ 240.,  324.,  420.],
       [ 900., 1056., 1224.]])

find net revenue (total revenue - discount)

In [16]:
net_revenue = q1_revenue - q1_discounts
net_revenue

array([[1600., 2112., 2200.],
       [ 960., 1296., 1680.],
       [3600., 4224., 4896.]])

In [17]:
np.sum(q1_discounts)

np.float64(5642.0)

In [18]:
np.sum(net_revenue)

np.float64(22568.0)

dot product between 2 metrics


In [24]:
features = np.array([
    [2000, 3], # house 1
    [1800, 4] # house 2
])

weights = np.array([150, 4000])
np.dot(features, weights) # house 1 = 2000*150 + 4000*3

array([312000, 286000])

cross product between 2 metrics

In [25]:
c= np.array([1,2,3])
d = np.array([4,5,6])

np.cross(c,d)

array([-3,  6, -3])