In [2]:
import numpy as np

In [6]:
q1 = np.array([
    [200,220,250],
    [150,180,210],
    [300,330,360]
])
q2 = np.array([
    [209,231,259],
    [155,192,222],
    [310,340,375]
])

add two

In [8]:
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [9]:
q2 -q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

to find the growth percentage from q1 to q2

In [10]:
 (q2 - q1)/q1 * 100

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [ ]:
prices = np.array([
    [10,12,11], # prices for product a in different region
    [8,9,10],   #product b
    [15,16,17]  #product c
])