In [2]:
import numpy as np
from numpy import dtype

In [5]:
rev_q1 = np.array([10,12,9])
rev_q1.ndim

1

In [7]:
rev = np.array([[10,12,9],[15,11,13]])
rev

array([[10, 12,  9],
       [15, 11, 13]])

In [8]:
rev[1,2]

np.int64(13)

In [9]:
rev[1,0] = 14
rev

array([[10, 12,  9],
       [14, 11, 13]])

In [10]:
rev.dtype

dtype('int64')

In [11]:
rev = np.array([[10,12,9],[15,11,13]], dtype=np.float64)
rev.dtype

dtype('float64')

item size means byte size of each element

In [12]:
rev.itemsize

8

size means how many items are there

In [13]:
rev.size

6

to identify the row and column

In [14]:
rev.shape

(2, 3)

sorting

In [15]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [16]:
np.sort(rev)

array([[ 9., 10., 12.],
       [11., 13., 15.]])

In [17]:
np.sort(rev, axis=None)

array([ 9., 10., 11., 12., 13., 15.])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [24]:
np.linspace(10,20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [25]:
rev.ravel()

array([10., 12.,  9., 15., 11., 13.])

In [26]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [27]:
rev.flatten()

array([10., 12.,  9., 15., 11., 13.])

In [32]:
rev.reshape(3,2)

array([[10., 12.],
       [ 9., 15.],
       [11., 13.]])

In [33]:
rev.min()

np.float64(9.0)

In [34]:
rev.max()

np.float64(15.0)

get the sum in horizontically

In [35]:
rev.sum(axis=1)

array([31., 39.])

get the sum in vertically


In [36]:
rev.sum(axis=0)

array([25., 23., 22.])

In [37]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [38]:
for row in rev:
    print("row:-> ", row)

row:->  [10. 12.  9.]
row:->  [15. 11. 13.]


In [41]:
b = np.array([1,4,16])

In [42]:
np.sqrt(b)

array([1., 2., 4.])

In [43]:
np.square(b)

array([  1,  16, 256])

In [44]:
np.std(b)

np.float64(6.48074069840786)