In [1]:
import numpy as np
from numpy.ma.core import argmax

In [2]:
a = np.array([6,7,8,9])

In [3]:
a[0:2]

array([6, 7])

In [4]:
a[2:]

array([8, 9])

In [5]:
a[-1]

np.int64(9)

In [6]:
a[-2:]

array([8, 9])

In [8]:
b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [9]:
b[1][2]

np.int64(6)

In [10]:
b[1,2]

np.int64(6)

In [11]:
b[2,0]

np.int64(7)

In [12]:
b[-1]

array([7, 8, 9])

In [13]:
b[-1, 0:2]

array([7, 8])

In [14]:
b[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
b[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [17]:
# Customer ID, name
c = np.array([
    [101,'Mira'],
    [102,'Abdul'],
    [103,'Andrea']
])

#customer ID, purchase amount and purchase date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
]
)

to merging 2 column in horizontal (basic)


In [19]:
np.hstack((c,d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [20]:
c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U21')

In [22]:
e= np.array([
    [104,'Venkat'],
    [105,'John'],
    [106,'Kathy']
])
e

array([['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

to merging 2 column in vertical (basic)

In [24]:
np.vstack((c,e))

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

to horizontal split

In [27]:
transactions = np.array([
    [101,'Mohan', 250.50, '2023-08-01'],
    [102,'Bob', 150.00, '2023-08-02'],
    [103, 'Fathima',300.75, '2023-08-01'],
    [104, 'David',400.75, '2023-08-03'],
    [105, 'Aryan',330.1, '2023-08-04'],
])
a, b= np.hsplit(transactions,2)


In [28]:
a

array([['101', 'Mohan'],
       ['102', 'Bob'],
       ['103', 'Fathima'],
       ['104', 'David'],
       ['105', 'Aryan']], dtype='<U32')

In [29]:
b

array([['250.5', '2023-08-01'],
       ['150.0', '2023-08-02'],
       ['300.75', '2023-08-01'],
       ['400.75', '2023-08-03'],
       ['330.1', '2023-08-04']], dtype='<U32')

In [33]:
x,y = np.vsplit(transactions,[2])

In [34]:
x

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')

In [35]:
y

array([['103', 'Fathima', '300.75', '2023-08-01'],
       ['104', 'David', '400.75', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [36]:
monthly_sales = np.array([30,33,35,28,42])

result = monthly_sales < 32
result

array([ True, False, False,  True, False])

In [37]:
monthly_sales[result]

array([30, 28])

In [40]:
index  = np.argmax(monthly_sales)
monthly_sales[index]

np.int64(42)

In [41]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fathima', '300.75', '2023-08-01'],
       ['104', 'David', '400.75', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [45]:
transactions[:,2].astype(float)

array([250.5 , 150.  , 300.75, 400.75, 330.1 ])

In [48]:
index = np.argmax(transactions[:,2].astype(float))
transactions[index]

array(['104', 'David', '400.75', '2023-08-03'], dtype='<U32')

In [50]:
transactions[transactions[:,0] == '102']

array([['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')